# Generated by Django 4.2.7 on 2023-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Производитель')),
                ('art', models.CharField(max_length=150, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('qty', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
                ('storage_location', models.CharField(max_length=100, verbose_name='Место хранения')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('supplier', models.TextField(verbose_name='Поставщик')),
                ('product_is_accepted', models.BooleanField(default=False)),
                ('warehouse', models.CharField(max_length=200, verbose_name='Склад хранения')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
    ]
