# Generated by Django 4.2.7 on 2023-11-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparts',
            options={'ordering': ['product_is_accepted', '-art'], 'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.RemoveField(
            model_name='autoparts',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='price',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место хранения'),
        ),
    ]
