# Generated by Django 4.2.7 on 2023-11-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparts',
            options={'ordering': ['product_is_accepted', '-art'], 'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
    ]
