# Generated by Django 4.2.7 on 2023-11-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена'),
        ),
    ]
