# Generated by Django 4.2.7 on 2023-11-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_autoparts_options_remove_autoparts_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='supplier',
            field=models.TextField(blank=True, null=True, verbose_name='Поставщик'),
        ),
    ]
