# Generated by Django 4.2.7 on 2023-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_autoparts_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='delivery_date',
            field=models.DateField(blank=True, default='нет данных', null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='storage_location',
            field=models.CharField(blank=True, default='нет данных', max_length=100, null=True, verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='supplier',
            field=models.TextField(blank=True, default='нет данных', null=True, verbose_name='Поставщик'),
        ),
    ]
