# Generated by Django 4.2.7 on 2023-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_autoparts_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='ref_storage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Изменённое место хранения'),
        ),
    ]
