# Generated by Django 4.2.7 on 2023-11-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_autoparts_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
    ]
